import type {NextPage} from "next";
import Head from "next/head";
import Register from "@/modules/register";

const RegisterPage: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Register/>
        </div>
    );
};

export default RegisterPage;
