import type {NextPage} from "next";
import Head from "next/head";
import Home from "@/modules/home";
import Layout from "@/components/layout";


const HomePage: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Layout>
                <Home/>
            </Layout>
        </div>
    );
};

export default HomePage;
